base/urls.py
from django.contrib import admin
from django.urls import path

from . import views
urlpatterns = [
    path('',views.home,name="home"),
    path('room/<str:pk>/',views.rooms,name="room"),
    path('create-room/',views.createRoom,name="create-room"),
    path('update-room/<str:pk>',views.updateRoom,name="updateRoom"),
    path('delete-room/<str:pk>',views.deleteRoom,name="deleteRoom"),
    path('login/',views.loginPage,name="login"),
    path('logout/',views.logoutUser,name="logout"),
    path('Userprofile/<str:pk>',views.Userprofile,name="user-profile"),
    path('topics',views.topics,name="topics"),
    path('activity',views.topics,name="activity")



]

codb/urls.py
from django.contrib import admin
from django.urls import path,include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls'))
]

theme/StudyBud/base/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',  views.getRoutes),
    path('rooms/', views.getRooms),
    path('rooms/<str:pk>/', views.getRoom),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL,null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL,null=True)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True,blank=True)
    participants = models.ManyToManyField(User,related_name='participants',blank=True)
    updates = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-updates','-created']

    def __str__(self):
        return self.name

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updates = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

   

    def __str__(self):
        return self.body[:50]




    
    

base/forms.py
from django.forms import ModelForm 
from .models import Room

class RoomForm(ModelForm):
    class Meta:
        model = Room
        
        fields = ['topic','name','description']

base/views.py
from django.shortcuts import render,redirect,HttpResponse
from .models import Room,Topic,Message
from .forms import RoomForm
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
# Create your views here.



def home(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ""
    datas = Room.objects.filter(Q(topic__name__contains=q) | 
    Q(name__icontains=q)|
    Q(description__icontains=q)
    )
    topics = Topic.objects.all()
    room_count= datas.count()
    
    room_messages = Message.objects.all()[:5]

    context = {'rooms':datas,'topics':topics,'room_count':room_count,'room_messages':room_messages}
    return render(request, 'index.html',context)
    
def rooms(request,pk):
    rooms = Room.objects.get(id=pk)
    room_messages = rooms.message_set.all().order_by('-created')
    participants = rooms.participants.all()

    context ={'rooms':rooms,'room_messages':room_messages,'participants':participants}

    if request.method == "POST":
        body=request.POST.get('body')
        message= Message.objects.create(
            user=request.user,room=rooms,body=body
        )
        return redirect('room',pk=rooms.id)

    return render(request,'room.html',context)
@login_required(login_url='loginPage')
def createRoom(request):
    form = RoomForm()
    if request.method == "POST":
        form = RoomForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    context = {'form':form}
    return render(request,'room_form.html',context)
@login_required(login_url='loginPage')
def updateRoom(request,pk):
    room = Room.objects.get(id=pk)
    form = RoomForm(instance=room)
    if request.user != room.host:
        return HttpResponse("You are not authenticated")
    context={'form':form}
    if request.method == "POST":
        form = RoomForm(request.POST,instance=room)
        if form.is_valid():
            form.save()
            return redirect('home')
    return render(request,'room_form.html',context)
@login_required(login_url='loginPage')
def deleteRoom(request,pk):
    room = Room.objects.get(id=pk)
    if request.method == "POST":
        room.delete()
        return redirect('home')
    if request.user != room.host:
        return HttpResponse("You are not authenticated")
    else:
        return render(request,'delete.html')
def loginPage(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        print(User.objects.all())
        try:
            user = User.objects.get(username=username)

        except:
            messages.error(request,"User doesnot exists")
        user = authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            return  redirect('home')



    context={}
    return render(request,'login_register.html',context)
@login_required(login_url='loginPage')
def logoutUser(request):
    logout(request)
    return redirect('home')

def Userprofile(request,pk):
    user= User.objects.get(id=pk)
    context ={'user':user}

    return render(request,'profile.html',context)
def topics(request):
    return render(request,'index.html')

theme/StudyBud/base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from base.models import Room
from .serializers import RoomSerializer
from base.api import serializers


@api_view(['GET'])
def getRoutes(request):
    routes = [
        'GET /api',
        'GET /api/rooms',
        'GET /api/rooms/:id'
    ]
    return Response(routes)


@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request, pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False)
    return Response(serializer.data)

templates/activity_component.html
<div class="activities">
    <div class="activities__header">
        <h2>Recent Activities</h2>
    </div>
    {% for message in room_messages %}
    <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
            <a href="{% url 'user-profile' message.user.id %}" class="roomListRoom__author">
                <div class="avatar avatar--small">
                    <img src="{{message.user.avatar.url}}" />
                </div>
                <p>
                    @{{message.user.username}}
                    <span>{{message.created|timesince}} ago</span>
                </p>
            </a>

            {% if request.user == message.user %}
            <div class="roomListRoom__actions">
                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                        <title>remove</title>
                        <path
                            d="M27.314 6.019l-1.333-1.333-9.98 9.981-9.981-9.981-1.333 1.333 9.981 9.981-9.981 9.98 1.333 1.333 9.981-9.98 9.98 9.98 1.333-1.333-9.98-9.98 9.98-9.981z">
                        </path>
                    </svg>
                </a>
            </div>
            {% endif %}

        </div>
        <div class="activities__boxContent">
            <p>replied to post “<a href="{% url 'room' message.room.id %}">{{message.room}}</a>”</p>
            <div class="activities__boxRoomContent">{{message.body}}</div>
        </div>
    </div>
    {% endfor %}

</div>

templates/delete.html
{% extends 'main.html'%}

{% block content %}

<form method="POST" action="">
    {% csrf_token %}
    <p> Are you  really want to delete{{obj}} </p>
    <a href="{{request.META.HTTP.REFERER}}">Go Back</a>
    <input type="submit" value="Confirm"/>

</form>
{% endblock %}

templates/feed_component.html
{% for room in rooms %}
<div class="roomListRoom">
    <div class="roomListRoom__header">
        <a href="{% url 'user-profile' room.host.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
                <img src="{{room.host.avatar.url}}" />
            </div>
            <span>@{{room.host.username}}</span>
        </a>
        <div class="roomListRoom__actions">
            <span>{{room.created|timesince}} ago</span>
        </div>
    </div>
    <div class="roomListRoom__content">
        <a href="{% url 'room' room.id %}">{{room.name}}</a>
    </div>
    <div class="roomListRoom__meta">
        <a href="{% url 'room' room.id %}" class="roomListRoom__joined">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>user-group</title>
                <path
                    d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z">
                </path>
                <path
                    d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z">
                </path>
                <path
                    d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z">
                </path>
                <path
                    d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z">
                </path>
            </svg>
            {{room.participants.all.count}} Joined
        </a>
        <p class="roomListRoom__topic">{{room.topic.name}}</p>
    </div>
</div>
{% endfor %}

templates/index.html
{% extends 'main.html' %}

{% block content %}

<main class="layout layout--3">
  <div class="container">

    <!-- Topics Start -->
    {% include 'topics_component.html' %}

    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form action="{% url 'home' %}" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="{% url 'topics' %}">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="{% url 'activity' %}">Recent Activities</a>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Study Rooms</h2>
          <p>{{room_count}} Rooms available</p>
        </div>

        <a class="btn btn--main" href="{% url 'create-room' %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z">
            </path>
          </svg>
          Create Room
        </a>
      </div>

      {% include 'feed_component.html' %}

    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'activity_component.html' %}

    <!-- Activities End -->
  </div>
</main>

{% endblock %}

templates/indexk.html
 {% extends 'main.html' %}
 
 {% block left %}
<div class="left_topic" >
 {% for topic in topics %}
 <div>
 <b><a href="{% url 'home' %}?q={{topic.name}}" style="color:#fff" class="btn-primary ">#{{topic}}</a></b>
 
 </div>
 {%endfor%}
</div>
 
 {% endblock%}

 {% block content %}
 <div class="input-group mb-3 w-3">
  
  
  <input type="text" class="form-control" aria-label="Text input with checkbox" placeholder="Whats your doubt">
</div>

   

  <a href="{% url 'createRoom'%}"  class="btn btn-secondary"/>Create Room</a>
 

 <hr>
 <b><h5> Rooms Available {{room_count}}</h5></b>
 {% for room in rooms%}
 
 <a href="{% url 'room' room.id%}" class="card-link">{{room.description}}</a><br>
<div style=" display: flex;
justify-content: space-between;
">
      <a href="{% url 'Userprofile' room.host.id%}">@{{room.host.username}}</a> <p style="text-size:5px">{{room.created|timesince}}</p>
        
</div>

      {%if request.user == room.host%}
      <a href="{% url 'deleteRoom' room.id%}" class="card-link">Delete Room</a>
      <a href="{% url 'updateRoom' room.id%}" class="card-link">Update Room</a>
      {%endif%}

<br/><hr/>


{% endfor %}

{% endblock %}

  {% block right %}
 <b> <p class="font-weight-bold">RECENT ACTIVITES</p></b>


  {% for messages in room_messages%}
  <div>
    <p class="font-weight-small">{{messages.body}}</p>

      
    </div>
    <div style=" display: flex;
    justify-content: space-between;
    ">
  <p class="font-weight-light">@{{messages.user}}.</p>
  <p>{{messages.created|timesince}}
    <p>{{messages.topic}}

  </div>
  
    <hr>
  {%endfor%}
  {% endblock %}





templates/login_register.html
{% extends 'main.html'%}
{% block content %}

<div>

{%if messages %}
{% for message in messages%}
{{message}}
{%endfor%}
{% endif %}
    <form method ="POST" action="">
        {% csrf_token %}
        <label>Username</label>
        <input type="text" value="username" placeholder ="Enter Username" name="username"/>
<label>Password </label>
<input type="password" value="password" placeholder="Enter Password" name="password"/>
<input type="Submit" value="Login"/>
    </form>
</div>


{% endblock%}

templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="assets/favicon.ico" type="image/x-icon" />
    <link rel="stylesheet" href="{% static 'styles/style.css' %}" />
    <title>RBITIANS - Make yourself skilled</title>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.css" rel="stylesheet" />

</head>

<script src="{% static 'js/script.js' %}"></script>

<body>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/1.6.3/flowbite.min.js"></script>

    {% include 'navbar.html' %}

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    {% block content %}


    {% endblock %}

</body>

</html>

templates/main.old.html
<!doctype html>
 {% load static %}
 <!DOCTYPE html>
 <html lang="en">
   
 <head>
	<style>
		.col{
			border:1px solid black;
			border-shadow:1px;
		}
	</style>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rbit</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>
  <script src="https://kit.fontawesome.com/c60c43416b.js" crossorigin="anonymous"></script>
 
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

  <body>
<div>
	<div class="container">

	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<a class="navbar-brand" href="{% url 'home'%}">Rbit</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		  <span class="navbar-toggler-icon"></span>
		</button>
	  
		<div class="collapse navbar-collapse" id="navbarSupportedContent">
		  <ul class="navbar-nav mr-auto">
			<li class="nav-item active">
			  <a class="nav-link" href="#">Welcome <span class="sr-only"> {{request.user.username}}</span></a>
			</li>
			<li class="nav-item">
			  <a class="nav-link" href="#">Queries</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="#">Profile</a>
			  </li>
			
			
		  </ul>
		 
		</div>
	  </nav>
	</div>
	
  
	<div class="row" >
		<div class="col" style="background-color:darkslateblue;font:aerial">
			<form class="form-inline my-2 my-lg-0" method="GET" action ={% url 'home' %}>
				<input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q">
				
			  </form>
		  {% block left %}
		  {% endblock %}
		</div>
		<div class="col-6" style="background-color: #8c8c8c

		;font:aerial">
		 {% block content %}
		  {% endblock%}
		</div>
		<div class="col">
		  {% block right%}
		  {% endblock %}
		</div>
	  </div>
   
    </div>
    

  </body>
</html>

templates/navbar.html
{% load static %}
<script src="{% static 'js/script.js' %}"></script>

<header class="header header--loggedIn">
    <div class="container">
        <a href="{% url 'home' %}" class="header__logo">
            <img src="{% static 'images/logo.svg' %}" />
            <h1>RBITIANS</h1>
        </a>
        <form class="header__search" method="GET" action="{% url 'home' %}">
            <label>
                <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                    <title>search</title>
                    <path
                        d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
                    </path>
                </svg>
                <input name="q" placeholder="Search for posts" />
            </label>
        </form>
        <nav class="header__menu">


            <!-- Logged In -->
            {% if request.user.is_authenticated %}
            <div class="header__user">
            
                    <div class="avatar avatar--medium active">
                        <img src="{{request.user.avatar.url}}" />
                    </div>
                    <p>{{request.user.username}} <span>@{{request.user.username}}</span></p>
                </a>
              
<button id="dropdownDefaultButton" data-dropdown-toggle="dropdown" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-4 py-2.5 text-center inline-flex items-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800" type="button"> <svg class="w-4 h-4 ml-2" aria-hidden="true" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 9l-7 7-7-7"></path></svg></button>
<!-- Dropdown menu -->
<div id="dropdown" class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow w-44 dark:bg-gray-700">
    <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
      <li>
        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Dashboard</a>
      </li>
      <li>
        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Settings</a>
      </li>
      <li>
        <a href="#" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Earnings</a>
      </li>
      <li>
        <a href="{%url 'logout'%}" class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Sign out</a>
      </li>
    </ul>
</div>

            </div>
            {% else %}

            <!-- Not Logged In -->
            <a href="{% url 'login' %}">
                <img src="{% static 'images/avatar.svg' %}" />
                <p>Login</p>
            </a>
            {% endif %}

            <div class="dropdown-menu">
             
                        <title>tools</title>
                        <path
                            d="M27.465 32c-1.211 0-2.35-0.471-3.207-1.328l-9.392-9.391c-2.369 0.898-4.898 0.951-7.355 0.15-3.274-1.074-5.869-3.67-6.943-6.942-0.879-2.682-0.734-5.45 0.419-8.004 0.135-0.299 0.408-0.512 0.731-0.572 0.32-0.051 0.654 0.045 0.887 0.277l5.394 5.395 3.586-3.586-5.394-5.395c-0.232-0.232-0.336-0.564-0.276-0.887s0.272-0.596 0.572-0.732c2.552-1.152 5.318-1.295 8.001-0.418 3.274 1.074 5.869 3.67 6.943 6.942 0.806 2.457 0.752 4.987-0.15 7.358l9.392 9.391c0.844 0.842 1.328 2.012 1.328 3.207-0 2.5-2.034 4.535-4.535 4.535zM15.101 19.102c0.26 0 0.516 0.102 0.707 0.293l9.864 9.863c0.479 0.479 1.116 0.742 1.793 0.742 1.398 0 2.535-1.137 2.535-2.535 0-0.668-0.27-1.322-0.742-1.793l-9.864-9.863c-0.294-0.295-0.376-0.74-0.204-1.119 0.943-2.090 1.061-4.357 0.341-6.555-0.863-2.631-3.034-4.801-5.665-5.666-1.713-0.561-3.468-0.609-5.145-0.164l4.986 4.988c0.391 0.391 0.391 1.023 0 1.414l-5 5c-0.188 0.188-0.441 0.293-0.707 0.293s-0.52-0.105-0.707-0.293l-4.987-4.988c-0.45 1.682-0.397 3.436 0.164 5.146 0.863 2.631 3.034 4.801 5.665 5.666 2.2 0.721 4.466 0.604 6.555-0.342 0.132-0.059 0.271-0.088 0.411-0.088z">
                        </path>
                    </svg>
                    Settings</a>
                <a href="{% url 'logout' %}" class="dropdown-link"><svg version="1.1" xmlns="http://www.w3.org/2000/svg"
                        width="32" height="32" viewBox="0 0 32 32">
                        <title>sign-out</title>
                        <path
                            d="M3 0h22c0.553 0 1 0 1 0.553l-0 3.447h-2v-2h-20v28h20v-2h2l0 3.447c0 0.553-0.447 0.553-1 0.553h-22c-0.553 0-1-0.447-1-1v-30c0-0.553 0.447-1 1-1z">
                        </path>
                        <path
                            d="M21.879 21.293l1.414 1.414 6.707-6.707-6.707-6.707-1.414 1.414 4.293 4.293h-14.172v2h14.172l-4.293 4.293z">
                        </path>
                    </svg>
                    Logout</a>
            </div>
        </nav>
    </div>
</header>



 {% if request.user.is_authenticated %}
<p>Hello {{request.user}}</p>
<a href="{% url 'logout' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}">Login</a>
{% endif %} 

templates/navbar.old.html
<!DOCTYPE html>

<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
      
        {% block navbar %}

        {% endblock %}
        
    </body>
</html>

templates/profile.html
{% extends 'main.html' %}

{% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include 'topics_component.html' %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="{{user.avatar.url}}" />
          </div>
        </div>
        <div class="profile__info">
          <h3>{{user.name}}</h3>
          <p>@{{user.username}}</p>
          {% if request.user == user %}
          <a href="{% url 'update-user' %}" class="btn btn--main btn--pill">Edit Profile</a>
          {% endif %}
        </div>
        <div class="profile__about">
          <h3>About</h3>
          <p>
            {{user.bio}}
          </p>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>
            Welcome to the group of rbitian
          </h2>
        </div>
      </div>
      {% include 'feed_component.html' %}


    </div>
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include 'activity_component.html' %}
    <!-- Activities End -->
  </div>
</main>
{% endblock content %}

templates/room.html
{% extends 'main.html'%}

{% block content %}
{{rooms}}
<b/>
{%for message in room_messages%}
<div>
@{{message.user}}

{{message.created|timesince}}
<div>
    {{message}}
</div>
</div>
{%endfor%}
<form method="POST">
    {% csrf_token %}
    <input type="text" name="body"/>
    <input type="Submit" value="Submit"/>
</form>
<div>
    {%for participant in participants%}
    {{participant}}
    {%endfor%}
</div>
{% endblock %}

templates/topics_component.html
<div class="topics">
    <div class="topics__header">
        <h2>Browse Topics</h2>
    </div>
    <ul class="topics__list">
        <li>
            <a href="{% url 'home' %}" class="active">All <span>{{topics.count}}</span></a>
        </li>
        {% for topic in topics %}
        <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{topic.name}}<span>{{topic.room_set.all.count}}</span></a>
        </li>
        {% endfor %}

    </ul>
    <a class="btn btn--link" href="{% url 'topics' %}">
        More
        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>chevron-down</title>
            <path d="M16 21l-13-13h-3l16 16 16-16h-3l-13 13z"></path>
        </svg>
    </a>
</div>